# frontend/Dockerfile
FROM nginx:alpine

# Copy the frontend files to the Nginx HTML directory
COPY . /usr/share/nginx/html
COPY ./styles.css /usr/share/nginx/html/frontend/styles.css


# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]