# docker-compose.yml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: knowtimeDB
      POSTGRES_USER: kt_admin
      POSTGRES_PASSWORD: TestMe123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SETTINGS_MODULE: "djangoConfig.settings"
      PYTHONPATH: "/app"
    volumes:
      - ./backend/login/fixtures/user_data.json:/app/login/fixtures/user_data.json
      - ./backend/grades/fixtures/grades_data.json:/app/grades/fixtures/grades_data.json

    command: >
      sh -c "
            while ! nc -z kt-db 5432; do sleep 1; done;
            python manage.py makemigrations &&
            python manage.py migrate &&
            python assignments/utility.py &&
            python grades/utility.py &&
            python taskboard/utility.py &&
            python courses/utility.py &&
            python manage.py loaddata /app/login/fixtures/user_data.json &&
            python manage.py loaddata /app/timer/fixtures/study_data.json &&
            python manage.py loaddata /app/grades/fixtures/grades_data.json &&
            python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:13
    container_name: kt-db
    environment:
      POSTGRES_DB: knowtime
      POSTGRES_USER: kt_admin
      POSTGRES_PASSWORD: TestMe123
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/config.sql:/docker-entrypoint-initdb.d/config.sql
          
    networks:
      - app-network

  test:
    build:
      context: .
      dockerfile: tests/Dockerfile.test
    depends_on:
      - backend
    command: pytest tests/

networks:
  app-network:
    driver: bridge
