# docker-compose.yml
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: knowtimeDB
      POSTGRES_USER: kt_admin
      POSTGRES_PASSWORD: TestMe123
      POSTGRES_HOST: my-postgres-container
      POSTGRES_PORT: 5432

  db:
    image: postgres:13
    container_name: kt-db
    environment:
      POSTGRES_DB: knowtime
      POSTGRES_USER: kt_admin
      POSTGRES_PASSWORD: TestMe123
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/config.sql:/docker-entrypoint-initdb.d/config.sql
          
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
