# docker-compose.yml
version: '311'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: knowtimeDB
      POSTGRES_USER: knowtimeAdmin
      POSTGRES_PASSWORD: TestMe123
      POSTGRES_HOST: my-postgres-container
      POSTGRES_PORT: 5432

  db:
    image: postgres:13
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: knowtimeDB
      POSTGRES_USER: knowtimeAdmin
      POSTGRES_PASSWORD: TestMe123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: