# backend/Dockerfile
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the backend code
COPY . .

# Run database migrations
RUN python manage.py migrate

# Expose port 8000
EXPOSE 8000

# Start the Django application using Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8000", "config.wsgi"]