# Generated by Django 5.1.2 on 2024-10-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('course_id', models.IntegerField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('points_possible', models.FloatField(blank=True, null=True)),
                ('grading_type', models.CharField(max_length=50)),
                ('submission_types', models.CharField(max_length=50)),
            ],
        ),
    ]
